import { Question } from './types';

export const INITIAL_SEED_QUESTIONS: Question[] = [
  {
    id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
    question: "Pod in Kubernetes stays stuck in CrashLoopBackOff with Exit Code 137. How do you diagnose and fix this in production?",
    question_type: "Troubleshooting Question",
    topic_name: "Kubernetes Engine",
    concept_name: "Pod CrashLoopBackOff & OOMKilled",
    experience_level_name: "Senior",
    priority_name: "Critical",
    status: "Active",
    source: "Production Outage Postmortem",
    language: "en",
    category: "Container Orchestration",
    subcategory: "Resource Management",
    cloud_provider: "Multi-Cloud",
    technology: "Kubernetes",
    difficulty: "Hard",
    tags: ["k8s", "crashloopbackoff", "oomkilled", "cgroups", "exit-code-137"],
    is_bookmarked: true,
    is_favorite: true,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    answer: {
      id: "a101-f47ac10b",
      question_id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
      flags: "• Exit Code 137 in kubectl describe pod <pod-name> indicating Linux cgroups OOM Killer invoked SIGKILL (128 + 9 = 137).\n• kubectl get events shows OOMKilled: Killing process (pid: 1042) in cgroup /kubepods/burstable.\n• Prometheus metric container_memory_working_set_bytes hits or exceeds kube_pod_container_resource_limits.\n• Gradual latency creep followed by sudden pod termination without application stack trace logs.",
      commands: "• kubectl get pod <pod-name> -n <namespace> -o jsonpath='{.status.containerStatuses[*].lastState.terminated}'\n  Verify exact container termination reason and exit code 137.\n• kubectl debug node/<node-name> -it --image=busybox -- dmesg -T | grep -i oom\n  Inspect Linux kernel dmesg logs for OOM invocation on the host node.\n• kubectl top pod <pod-name> -n <namespace> --containers\n  Retrieve live container memory working set vs allocated memory limit.\n• kubectl exec -it <pod-name> -n <namespace> -- curl -s http://localhost:6060/debug/pprof/heap > heap.pprof\n  Capture Go or JVM memory heap profile before OOM crash.",
      dependency_check: "• Ingress / Service Mesh: Upstream Envoy/Nginx proxy will log 502 Bad Gateway or 503 Service Unavailable during pod restarts.\n• Database Connections: Sudden SIGKILL aborts open TCP connections without sending FIN/RST, leading to orphaned pool connections on PostgreSQL/Redis.\n• Rollback Risk: Rolling back deployment without increasing memory limits will not resolve non-deterministic heap memory leaks.",
      fix: "1. Immediate Emergency Tuning: Set memory limit to 2Gi using kubectl set resources deployment/<deploy-name> -n <namespace> -c=<container-name> --limits=memory=2Gi --requests=memory=1Gi.\n2. Implement Vertical Pod Autoscaler (VPA) in Recommendation Mode to observe real working-set memory patterns.\n3. Application Code Fix: Patch memory leakage (unclosed file descriptors or unconstrained async caching loops).\n4. Post-Fix Verification: Monitor container_memory_working_set_bytes for 48 hours to ensure memory plateaus safely below 75% of limit.",
      root_cause: "• Container Memory Limit Misconfiguration: Application JVM/Go runtime allocated default OS memory parameters exceeding cgroup v2 limits.\n• Native Off-Heap Memory Leak: Unmanaged C-extensions or unbounded buffering.\n• Node Pressure: Node kernel executing OOM killer under total memory pressure when pods lack explicit requests/limits.",
      precautions: "• Enforce LimitRanges and ResourceQuotas per namespace in CI/CD pipeline validation checks.\n• Set Alertmanager alerts for container_memory_working_set_bytes / limit > 0.85 for > 5m.\n• Configure JVM -XX:MaxRAMPercentage=75.0 so garbage collection kicks in before container cgroup limit is hit.",
      indications: "• Steady upward trend line in container_memory_working_set_bytes without dropping after garbage collection cycles.\n• Pod restart count steadily incrementing over a 6-hour window.\n• Spike in node_vmstat_pgmajfault (major page faults) prior to pod kill.",
      interview_perspective: "• Direct Verbal Response: 'When I troubleshoot Exit Code 137, I immediately isolate whether SIGKILL was dispatched by the OS kernel due to node-level memory pressure or by cgroups container_memory_working_set_bytes breaching pod spec limits. I query Prometheus for container_memory_working_set_bytes vs kube_pod_container_resource_limits. If limits are hit, I apply immediate emergency buffer room while capturing a pprof heap profile before patching application leaks.'\n• Architectural Trade-offs: 'Raising limits is a short-term band-aid. Increasing limits without VPA recommendation data increases cluster node fragmentation and cost. Conversely, leaving limits uncapped risks BestEffort pod evictions under node pressure.'\n• Production Triage Framework: '1. Fast Triage (check describe pod & lastState.terminated). 2. MTTR Mitigation (temporarily raise memory limits & scale replicas). 3. Artifact Capture (dmesg & pprof heap dumps). 4. Long-term Guardrail (JVM MaxRAMPercentage=75.0 & LimitRanges in CI/CD).'",
      last_updated: new Date().toISOString(),
      edited_by: "Senior Principal SRE"
    }
  },
  {
    id: "a81bc20c-69dd-5483-b678-1f03c3d4e580",
    question: "Terraform apply fails with error: 'Error acquiring the state lock'. How do you resolve this safely in an automated CI/CD pipeline?",
    question_type: "Troubleshooting Question",
    topic_name: "Infrastructure as Code",
    concept_name: "Terraform State Drift & Lock Concurrency",
    experience_level_name: "Mid-Level",
    priority_name: "High",
    status: "Active",
    source: "CI/CD Pipeline Failure",
    language: "en",
    category: "Automation",
    subcategory: "Terraform / OpenTofu",
    cloud_provider: "AWS",
    technology: "Terraform",
    difficulty: "Medium",
    tags: ["terraform", "state-lock", "dynamodb", "s3-backend", "ci-cd"],
    is_bookmarked: false,
    is_favorite: true,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    answer: {
      id: "a102-a81bc20c",
      question_id: "a81bc20c-69dd-5483-b678-1f03c3d4e580",
      flags: "• CI/CD pipeline runner times out with Error acquiring the state lock: ConditionalCheckFailedException.\n• Lock Info shows active Lock ID, Path, and runner process owner in DynamoDB terraform-locks table.\n• Pipeline job abruptly canceled or runner instance preempted mid-execution.",
      commands: "• aws dynamodb get-item --table-name terraform-locks --key '{\"LockID\": {\"S\": \"my-org-tf-state/prod/terraform.tfstate-md5\"}}'\n  Verify if the lock owner process is still registered in DynamoDB.\n• terraform force-unlock -force e4b8a21f-891d-403d-bc87-11f8b3d0124a\n  Release lock safely using Terraform CLI force-unlock.",
      dependency_check: "• Blast Radius Danger: Executing force-unlock while another CI job or teammate is actively executing terraform apply WILL result in corrupted terraform.tfstate or duplicate cloud resources.\n• Concurrency Verification: Always verify pipeline process isolation and ensure lock owner is 100% dead before breaking lock.",
      fix: "1. Inspect CI runner log to verify if runner crashed or suffered an unhandled SIGKILL.\n2. Confirm no concurrent PR or pipeline execution is running against the same environment.\n3. Execute terraform force-unlock <LOCK-ID> with proper team authorization.\n4. Run terraform plan to verify state integrity prior to resuming apply.",
      root_cause: "• Pipeline execution was abruptly terminated before Terraform executed cleanup hooks to delete the lock row in DynamoDB.",
      precautions: "• Wrap Terraform invocations in CI scripts with trap handlers to catch signals (trap 'terraform force-unlock ...' EXIT SIGINT SIGTERM).\n• Implement Atlantis or Terraform Cloud concurrency controls to guarantee single-tenant execution queues per workspace.\n• Set S3 bucket versioning on state buckets for 1-click state rollback if corruption ever occurs.",
      indications: "• High pipeline cancellation rates by developers.\n• Flaky runner instances or runner node preemptions during terraform execution phases.",
      interview_perspective: "• Direct Verbal Response: 'When I hit a Terraform state lock in a production CI/CD pipeline, I never blindly execute force-unlock. My first step is querying the DynamoDB locking table to extract the LockID and process owner. I verify whether the CI runner pod was preempted or killed via SIGKILL. Once I verify no active process is mutating state, I break the lock with terraform force-unlock and immediately run terraform plan to validate state hash checksums against S3 version history.'\n• Architectural Trade-offs: 'Relying on manual lock-breaking in DynamoDB is an operational anti-pattern. The architectural alternative is enforcing single-tenant deployment queues via Atlantis or Terraform Cloud workspaces, combined with S3 object versioning for instant state rollback.'\n• Production Triage Framework: '1. Lock Owner Verification (query DynamoDB & runner status). 2. Force-Unlock Safety Check (ensure zero concurrent state writes). 3. State Hash Validation (run terraform plan). 4. Pipeline Resilience (add SIGTERM trap handlers to CI scripts).'",
      last_updated: new Date().toISOString(),
      edited_by: "Lead Infra Architect"
    }
  },
  {
    id: "b92cd31d-70ee-6594-c789-2g04d4e5f691",
    question: "Explain BGP routing vs Static Routing in cloud networks (AWS Transit Gateway / Direct Connect). How do you achieve high-availability multi-region connectivity?",
    question_type: "Interview Question",
    topic_name: "Cloud Networking",
    concept_name: "BGP Routing & Transit Gateway HA Architecture",
    experience_level_name: "Lead / Principal",
    priority_name: "Medium",
    status: "Active",
    source: "AWS Principal Architect Interview",
    language: "en",
    category: "Networking & Security",
    subcategory: "HYBRID CLOUD / BGP",
    cloud_provider: "AWS",
    technology: "AWS Transit Gateway",
    difficulty: "Expert",
    tags: ["bgp", "aws", "transit-gateway", "direct-connect", "networking", "vpc"],
    is_bookmarked: true,
    is_favorite: false,
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 20).toISOString(),
    answer: {
      id: "a103-b92cd31d",
      question_id: "b92cd31d-70ee-6594-c789-2g04d4e5f691",
      flags: "• Sub-second failover requirement across dual AWS Direct Connect (DX) locations.\n• Asymmetric routing issues causing stateful firewall drops.\n• BGP session flapping logged in AWS CloudWatch / Router SYSLOG.",
      commands: "• aws ec2 search-transit-gateway-routes --transit-gateway-route-table-id tgw-rtb-0123456789abcdef0 --filters Name=state,Values=active\n  Inspect AWS Transit Gateway active route tables and BGP propagated routes.\n• aws directconnect describe-direct-connect-gateway-attachments\n  Check BGP session state on Direct Connect Virtual Interface (VIF).",
      dependency_check: "• Asymmetric Traffic Flow: If BGP AS-Path prepending or MED is incorrectly set, ingress traffic will use Path A while egress traffic uses Path B, breaking stateful firewalls.",
      fix: "1. Dual Direct Connect + BGP: Provision 2 Direct Connect connections at 2 geographically separate DX locations.\n2. Transit Gateway (TGW) Peering: Peer TGW in Region A with TGW in Region B over AWS backbone.\n3. BGP Local Preference & MED:\n   - Primary Link: Announce with higher BGP Local Preference (e.g. 200).\n   - Backup Link: Use AS-Path Prepending (prepend local ASN 3 times).",
      root_cause: "• Static Routing: Fixed CIDR routes configured manually. Zero control overhead, but lacks automatic failover.\n• Dynamic BGP: Exchanging IP prefixes dynamically via ASNs. Automatically recalculates paths within seconds upon link failure.",
      precautions: "• Configure Bidirectional Forwarding Detection (BFD) over BGP sessions to reduce failure detection time from 90s to under 300ms.\n• Enable AWS Transit Gateway Network Manager telemetry for real-time path visibility.",
      indications: "• BGP HoldTimer expiring events in Router logs.\n• Packet loss spikes on primary DX circuit prior to total link drop.",
      interview_perspective: "• Direct Verbal Response: 'In multi-region enterprise cloud networks, I design connectivity around 3 core pillars: BFD-backed BGP failover, traffic symmetry, and Transit Gateway route domain isolation. Static routing fails in production because it lacks link health monitoring. With dynamic BGP over dual AWS Direct Connect circuits, BGP automatically recalculates active routes in under 300ms using BFD when a fiber cut occurs.'\n• Architectural Trade-offs: 'Static Routing provides deterministic control and zero BGP session overhead, but requires manual route table intervention during outages. Dynamic BGP provides sub-second failover, but requires strict AS-Path prepending and Local Preference policies to prevent asymmetric routing across stateful firewalls.'\n• Production Triage Framework: '1. Link Health Telemetry (monitor BFD session timers & CloudWatch VIF metrics). 2. Symmetry Enforcement (align Local Pref for ingress with AS-Path prepending for egress). 3. Blast Radius Isolation (isolate dev/prod route tables on Transit Gateway).'",
      last_updated: new Date().toISOString(),
      edited_by: "Principal Network Architect"
    }
  }
];
